image:
  registry: docker.io
  repository: bitnami/wordpress
  tag: 5-debian-10
  pullPolicy: IfNotPresent

wordpressSkipInstall: false

ingress:
  enabled: true
  certManager: true
  hostname: SERVER_NAME
  tls: true
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"

service:
  type: ClusterIP

mariadb:
  enabled: true
  architecture: standalone
  auth:
    rootPassword: "super-secret"
    database: bitnami_wordpress
    username: bn_wordpress
    password: "super-secret"
  primary:
    persistence:
      enabled: true
      storageClass: "nfs-client"
      size: 10Gi

persistence:
  enabled: true
  annotations:
    helm.sh/resource-policy: "keep"
  storageClass: "nfs-client"
  size: 10Gi

